apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memgraph-pvc
  namespace: autoweave-memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: memgraph
  namespace: autoweave-memory
  labels:
    app: memgraph
    component: graph-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memgraph
  template:
    metadata:
      labels:
        app: memgraph
        component: graph-database
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: memgraph
        image: memgraph/memgraph:2.18.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7687
          name: bolt
        - containerPort: 7444
          name: http
        env:
        - name: MEMGRAPH_USER
          valueFrom:
            configMapKeyRef:
              name: memory-config
              key: MEMGRAPH_USER
        - name: MEMGRAPH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: memory-secrets
              key: MEMGRAPH_PASSWORD
        - name: MEMGRAPH_DATABASE
          valueFrom:
            configMapKeyRef:
              name: memory-config
              key: MEMGRAPH_DATABASE
        - name: MEMGRAPH_LOG_LEVEL
          value: "INFO"
        - name: MEMGRAPH_STORAGE_MODE
          value: "IN_MEMORY_ANALYTICAL"
        volumeMounts:
        - name: memgraph-data
          mountPath: /var/lib/memgraph
        - name: memgraph-log
          mountPath: /var/log/memgraph
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 7687
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 60
      volumes:
      - name: memgraph-data
        persistentVolumeClaim:
          claimName: memgraph-pvc
      - name: memgraph-log
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: memgraph-service
  namespace: autoweave-memory
  labels:
    app: memgraph
    component: graph-database
spec:
  type: ClusterIP
  selector:
    app: memgraph
  ports:
  - name: bolt
    port: 7687
    targetPort: 7687
    protocol: TCP
  - name: http
    port: 7444
    targetPort: 7444
    protocol: TCP