apiVersion: v1
kind: Service
metadata:
  name: memgraph-monitoring
  namespace: autoweave-memory
  labels:
    app: memgraph
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: memgraph
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: qdrant-monitoring
  namespace: autoweave-memory
  labels:
    app: qdrant
    component: monitoring
spec:
  type: ClusterIP
  selector:
    app: qdrant
  ports:
  - name: metrics
    port: 6333
    targetPort: 6333
    protocol: TCP
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: memory-system-monitor
  namespace: autoweave-memory
  labels:
    app: memory-system
    component: monitoring
spec:
  selector:
    matchLabels:
      component: graph-database
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: qdrant-monitor
  namespace: autoweave-memory
  labels:
    app: qdrant
    component: monitoring
spec:
  selector:
    matchLabels:
      component: vector-database
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: memory-backup
  namespace: autoweave-memory
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: alpine:latest
            command:
            - /bin/sh
            - -c
            - |
              echo "Starting memory system backup..."
              
              # Create backup directory
              mkdir -p /backup/$(date +%Y%m%d)
              
              # Backup Memgraph (simplified)
              echo "Backing up Memgraph..."
              # Note: In production, use proper Memgraph backup tools
              
              # Backup Qdrant (simplified)
              echo "Backing up Qdrant..."
              # Note: In production, use proper Qdrant backup tools
              
              echo "Backup completed"
            volumeMounts:
            - name: backup-storage
              mountPath: /backup
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName: backup-pvc
          restartPolicy: OnFailure
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: autoweave-memory
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi